version: "3"
services:
  demo-app:
    build: .
    volumes:
      - .:/src
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
    environment:
      - LOG_LEVEL:debug
      - WEB_CONCURRENCY:2
    command: > # uvicornのサーバーを立ち上げる
      poetry run
      uvicorn app.api:app
      --host 0.0.0.0 --reload
